preview = true
output-format = "pylint"
[lint]
select = [         
    "E","F821","F521","F522","F523","F524","F525","F541","F601","F602","F622","F701","F702","F704","F706","F722","F822",
    "F823","F901"
]
ignore = ["E501","E402","E201","E202","E251","E252","E261","E262","E265","E305","E231","E203","E202",
          "E713","E714","E731","E741","E742","E743","E302","E303"]
